name: VAOT Proposal

concurrency:
  group: ${{ github.ref_name }}
  cancel-in-progress: true

on:
  workflow_call:
    inputs:
      published_module_id:
        required: true
        type: string
      published_lua_code_id:
        required: false
        type: string

jobs:
  propose:
    runs-on: ubuntu-latest
    if:
      github.ref_name == 'main' || github.ref_name == 'develop' ||
      github.event_name == 'workflow_dispatch'
    environment: ${{ github.ref_name}}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4.0.2
        with:
          node-version-file: '.nvmrc'
          cache: 'yarn'
      - run: yarn --frozen-lockfile
      - run: yarn propose-version
        env:
          WALLET: ${{ secrets.WALLET }}
          REGISTRY_ID: ${{ vars.REGISTRY_ID }}
          VAOT_ID: ${{ vars.VAOT_ID}}
          MODULE_ID: ${{ inputs.published_module_id }}
          LUA_SOURCE_ID: ${{ inputs.published_lua_code_id }}
      - name: Notify Success
        if: success()
        uses: rtCamp/action-slack-notify@v2.3.0
        env:
          SLACK_COLOR: ${{ job.status }}
          SLACK_TITLE: ANT Version Proposed to ANT Registry Process!
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_CUSTOM_PAYLOAD: |
            {
              "attachments": [{
                "fallback": "ANT Version Proposed for ANT Registry!",
                "color": "good",
                "title": "Details",
                "text": 'The ANT Registry ${{ github.ref_name == 'main' && 'Testnet' || 'Devnet' }} Process has an ANT version update Proposal!',
                "fields": [{
                  "title": "Network",
                  "value": "${{ github.ref_name == 'main' && 'testnet' || 'devnet' }}",
                  "short": true
                },
                {
                  "title": "Process ID",
                  "value": "${{ vars.REGISTRY_ID }}",
                  "short": true
                },
                {
                  "title": "View on ao.link",
                  "value": "https://www.ao.link/#/entity/${{ vars.REGISTRY_ID }}?tab=source-code",
                  "short": false
                },
                 {
                  "title": "Vote on this proposal in VAOT",
                  "value": "https://vaot.ar.io/#/${{ vars.VAOT_ID }}",
                  "short": false
                },
                {
                  "title": "Commit",
                  "value": "<https://github.com/${{ github.repository }}/commit/${{ github.sha }}|${{ github.sha }}>"
                }
                ]
              }]
            }

      - name: Notify Failure
        if: failure()
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_COLOR: danger
          SLACK_TITLE: ANT Registry Process ANT version update Proposal FAILED!
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_CUSTOM_PAYLOAD: |
            {
              "text": "ANT Registry Process ANT Version Proposal Failed!",
              "attachments": [{
                "fallback": "Failed to propose ANT version update to ANT Registry!",
                "color": "danger",
                "title": "Details",
                "text": 'The ANT Registry ${{ github.ref_name == 'main' && 'Testnet' || 'Devnet' }} Process FAILED to create a version update Proposal!',
                "fields": [{
                  "title": "Network",
                  "value": "${{ github.ref_name == 'main' && 'testnet' || 'devnet' }}",
                  "short": true
                },
                {
                  "title": "Process ID",
                  "value": "${{ vars.REGISTRY_ID }}",
                  "short": true
                },
                {
                  "title": "GitHub Action",
                  "value": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}",
                  "short": false
                },
                {
                  "title": "Commit",
                  "value": "<https://github.com/${{ github.repository }}/commit/${{ github.sha }}|${{ github.sha }}>"
                }
                ]
              }]
            }
